export enum CriterioDesempate {
  VITORIAS = 'VITORIAS',
  SALDO_GOLS = 'SALDO_GOLS',
  GOLS = 'GOLS',
  ASSISTENCIAS = 'ASSISTENCIAS',
  APROVEITAMENTO = 'APROVEITAMENTO',
  MENOS_PARTIDAS = 'MENOS_PARTIDAS',
}
