export enum StatusParticipantePelada {
  CONFIRMADO = 'CONFIRMADO',
  PRESENTE = 'PRESENTE',
  AUSENTE = 'AUSENTE',
  DESISTIU = 'DESISTIU',
  JOGANDO = 'JOGANDO',
  AGUARDANDO = 'AGUARDANDO',
  DESCANSANDO = 'DESCANSANDO',
}
